'use client';

import { useState } from 'react';
import Image, { type ImageProps } from 'next/image';

/** Responsive variants are generated by Next; callers keep control over crop and priority. */
export default function MediaImage({
  width = 800,
  height = 800,
  sizes = '(max-width: 700px) 90vw, (max-width: 1000px) 45vw, 35vw',
  loading,
  ...props
}: ImageProps) {
  const [failedSource, setFailedSource] = useState<ImageProps['src'] | null>(null);
  const failed = failedSource === props.src;
  return (
    <Image
      width={width}
      height={height}
      sizes={sizes}
      loading={loading ?? (props.fetchPriority === 'high' ? 'eager' : 'lazy')}
      {...props}
      src={failed ? '/assets/product-placeholder.svg' : props.src}
      onError={() => setFailedSource(props.src)}
    />
  );
}
